-- SELECT * FROM cadastro;
-- SELECT * FROM produtos;
-- SELECT * FROM itens_carrinho;
-- SELECT * FROM comentarios;
-- SELECT * FROM categoria;
-- DROP TABLE nome_da_tabela;
-- DELETE FROM usuarios WHERE id = 1;
-- UPDATE usuarios SET nome = 'Ana Souza' WHERE id = 1;